version: '3'

services:
  server:
    image: cloud-storage-server
    build: ./
    container_name: cloud-storage-server
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/postgres
      spring.jpa.hibernate.ddl-auto: update
    ports:
      - "8090:8090"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    extra_hosts:
      - "postgres:172.17.0.1"
    ports:
      - "5432:5432"

